### ISSUE TITLE
Login error message is whack

### ISSUE THREAD

**Issue by MilisaSithole** [SeanWits/sdp_project#31]
![image](https://github.com/user-attachments/assets/dc89ae48-4835-4b21-b5fc-befe98d671f6)

Lock in

**Comment by refiloemopeloa** [comment]
# Resolved

## Issue

Notifying the user about a firebase related error.

## Solution

Changed the error message to a more user friendly message.

![image](https://github.com/user-attachments/assets/4f607db7-0c33-4734-b90c-f9cc0d930a38)
